security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
    
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/event/(\d+)$, roles: PUBLIC_ACCESS }  # Voir un événement spécifique
        - { path: ^/event, roles: ROLE_USER }  # Toutes les autres routes d'événements
        - { path: ^/game/(\d+)$, roles: PUBLIC_ACCESS }  # Voir un jeu spécifique
        - { path: ^/game, roles: ROLE_USER }  # Toutes les autres routes de jeux
        - { path: ^/, roles: ROLE_USER }  # Toutes les autres routes nécessitent une connexion

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
