<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTYCFSm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTYCFSm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTYCFSm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTYCFSm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJTYCFSm\App_KernelDevDebugContainer([
    'container.build_hash' => 'JTYCFSm',
    'container.build_id' => '2d0e8c98',
    'container.build_time' => 1737101045,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTYCFSm');
