<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRSi1v6l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRSi1v6l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRSi1v6l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRSi1v6l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRSi1v6l\App_KernelDevDebugContainer([
    'container.build_hash' => 'RSi1v6l',
    'container.build_id' => '8ef3a788',
    'container.build_time' => 1737091969,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRSi1v6l');
